events { worker_connections 1024; }

http { include /etc/nginx/mime.types; default_type application/octet-stream;

sendfile on; tcp_nopush on; tcp_nodelay on; keepalive_timeout 65; types_hash_max_size 2048;

server { listen 8080; # Listen on port 8080 server_name localhost;

root /usr/share/nginx/html; index index.html index.htm;

location / { try_files $uri $uri/ =404; } } }